US20 - View list of letter's templates,US22 - Update letter's templat…
Island-of-code/Sandbox2021Oct pull request #26
Opened 2021-11-03 06:53 UTC by Qosimjon1997

…e and US23 - Delete letter's template

2021-11-03 18:44 UTC, apilatau requested changes

2021-11-04 05:58 UTC, Qosimjon1997 commented on BusinessLayer/LetterTempService.cs
> +                throw new ArgumentNullException(nameof(lettersTemp));
Add template is not my task. It was Oybek's task. I created it only for check my task. Ok I remove it.

2021-11-04 06:04 UTC, Qosimjon1997 commented on WebAppAPI/Controllers/LetterTempController.cs
> +            return NoContent();
Ok I will change it.

2021-11-04 06:12 UTC, Qosimjon1997 commented on WebAppAPI/Controllers/LetterTempController.cs
> +            return NoContent();
Ok, I will send changed item to front-end.

2021-11-05 15:30 UTC, merged